### JAX Implementation experimentation

Below I will first eperiment with different sparse matrix structures available in JAX and then I will work on converting all the main functions to Jax sparse format. I will be optimising Markov_mfpt_cal, compute_free_energy, try_and_optim_MM and others.

In [3]:
import jax.experimental.sparse as jes
import jax.numpy as jnp
from jax import random
import jax.experimental.sparse.csr as csr
from scipy.sparse import random
from scipy.sparse.linalg import eigs

In [4]:
csr.CSR(BCOO_test)

TypeError: CSR.__init__() missing 1 required keyword-only argument: 'shape'

In [3]:
BCOO_test = jes.random_bcoo(random.PRNGKey(0),shape=(10000,10000))

/home/gsaba/miniconda3/envs/biophys_env/lib/python3.11/site-packages/jax/experimental/sparse/random.py:86: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'>  is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  data = generator(data_key, shape=data_shape, dtype=dtype, **kwds)


In [2]:
normal_csr_test = random(1000,1000,density=0.2)

In [23]:
BCOO_test.matvec

AttributeError: 'BCOO' object has no attribute 'matvec'

In [4]:
%%time
jes.linalg.linalg.eigs(normal_csr_test)

CPU times: user 6.99 s, sys: 17 s, total: 24 s
Wall time: 2.69 s


(array([100.06540458+0.j        ,   3.40916759+6.9502882j ,
          3.40916759-6.9502882j ,   7.70328054+0.j        ,
          0.20328932+7.55916309j,   0.20328932-7.55916309j]),
 array([[ 0.02713508+0.j        , -0.01511249-0.00879057j,
         -0.01511249+0.00879057j,  0.00409848+0.j        ,
         -0.00871203-0.00102738j, -0.00871203+0.00102738j],
        [ 0.02976233+0.j        , -0.02410505-0.01201209j,
         -0.02410505+0.01201209j,  0.03043427+0.j        ,
          0.01464009+0.00161577j,  0.01464009-0.00161577j],
        [ 0.02862622+0.j        , -0.00400549-0.03122786j,
         -0.00400549+0.03122786j, -0.03057455+0.j        ,
         -0.01222298+0.00755266j, -0.01222298-0.00755266j],
        ...,
        [ 0.03391066+0.j        , -0.02452753-0.03077573j,
         -0.02452753+0.03077573j,  0.00623749+0.j        ,
         -0.04350263-0.03361048j, -0.04350263+0.03361048j],
        [ 0.03305111+0.j        , -0.02330882+0.01662135j,
         -0.02330882-0.01662135j, 

In [5]:
%%time
eigs(normal_csr_test)

CPU times: user 5.45 s, sys: 16.9 s, total: 22.3 s
Wall time: 1.62 s


(array([100.06540458+0.j        ,   0.20328932+7.55916309j,
          0.20328932-7.55916309j,   7.70328054+0.j        ,
         -6.71714218+3.486716j  ,  -6.71714218-3.486716j  ]),
 array([[ 0.02713508+0.j        , -0.00872776-0.00088381j,
         -0.00872776+0.00088381j,  0.00409848+0.j        ,
         -0.0030725 +0.04991164j, -0.0030725 -0.04991164j],
        [ 0.02976233+0.j        ,  0.01466471+0.00137453j,
          0.01466471-0.00137453j,  0.03043427+0.j        ,
         -0.0082053 -0.02453507j, -0.0082053 +0.02453507j],
        [ 0.02862622+0.j        , -0.01209698+0.00775286j,
         -0.01209698-0.00775286j, -0.03057455+0.j        ,
          0.00962322-0.02494968j,  0.00962322+0.02494968j],
        ...,
        [ 0.03391066+0.j        , -0.04405006-0.03288974j,
         -0.04405006+0.03288974j,  0.00623749+0.j        ,
         -0.0058116 +0.01184868j, -0.0058116 -0.01184868j],
        [ 0.03305111+0.j        , -0.00472165-0.0107906j ,
         -0.00472165+0.0107906j , 

In [ ]:
jes.linalg.linag.eigs()