In [1]:
#test book for george get_working_MM()
import sys
import numpy as np


In [7]:
def get_working_MM(M):
    zero_rows = np.where(~M.any(axis=1))[0]
    zero_cols = np.where(~M.any(axis=0))[0]
    print(zero_cols, zero_rows)
    print(np.union1d(zero_rows, zero_cols))

    keep_indices = np.setdiff1d(range(M.shape[0]), np.union1d(zero_rows, zero_cols))
    print(keep_indices)
    M_work = M[np.ix_(keep_indices, keep_indices)]
    return M_work, keep_indices

def get_working_MM_intersect(M):
    zero_rows = np.where(~M.any(axis=1))[0]
    zero_cols = np.where(~M.any(axis=0))[0]

    keep_indices = np.intersect1d(range(M.shape[0]), np.union1d(zero_rows, zero_cols))
    M_work = M[np.ix_(keep_indices, keep_indices)]
    return M_work, keep_indices

def get_working_MM_v2(M):
    # Identify non-zero rows and columns
    non_zero_rows = np.where(M.any(axis=1))[0]
    non_zero_cols = np.where(M.any(axis=0))[0]
    
    # Filter the matrix to keep only non-zero rows and columns
    M_work = M[np.ix_(non_zero_rows, non_zero_cols)]
    
    return M_work, non_zero_rows, non_zero_cols

In [8]:
MM = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0]])

In [9]:
test_MM_2 = np.array([[0.1, 0.2, 0.0, 0.7],
                    [0.0, 0.0, 0.0, 0.0], 
                    [0.3, 0.0, 0.4, 0.3],
                    [0.0, 0.0, 0.0, 0.0]])

In [10]:
test_MM_2

array([[0.1, 0.2, 0. , 0.7],
       [0. , 0. , 0. , 0. ],
       [0.3, 0. , 0.4, 0.3],
       [0. , 0. , 0. , 0. ]])

In [11]:
get_working_MM(test_MM_2)

[] [1 3]
[1 3]
[0 2]


(array([[0.1, 0. ],
        [0.3, 0.4]]),
 array([0, 2]))

In [13]:
get_working_MM_v2(test_MM_2)

(array([[0.1, 0.2, 0. , 0.7],
        [0.3, 0. , 0.4, 0.3]]),
 array([0, 2]),
 array([0, 1, 2, 3]))

In [7]:
get_working_MM_intersect(MM)

(array([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0]]),
 array([0, 1, 3, 4, 5, 7, 8, 9]))