In [24]:
import numpy as np

def jjhunter(P):
    P = np.array(P, dtype=np.float64)  # Using double precision
    m = len(P)
    I = np.eye(m, dtype=np.float64)
    e1 = np.ones((m, 1), dtype=np.float64)
    E = np.ones((m, m), dtype=np.float64)
    PPD = P.copy()
    AASD = np.zeros((m, m), dtype=np.float64)
    SD = np.zeros(m)

    for n in range(m-1, 0, -1):
        #print(n,PPD[n, :n])
        SD[n] = np.sum(PPD[n, :n])
        #print(SD)
        for i in range(n):
            for j in range(n):
                AASD[i, j] = PPD[i, n] * PPD[n, j] / SD[n]
                PPD[i, j] += AASD[i, j]
    #print(AASD,'\n', PPD)

    rD = np.zeros(m, dtype=np.float64)
    rD[0] = 1
    for n in range(1, m):
        for i in range(n):
            rD[n] += rD[i] * PPD[i, n] / SD[n]
    #print(rD)

    TOTD = np.sum(rD)
    pit_1D = rD / TOTD
    PiD = e1 @ pit_1D.reshape(1, -1)
    #print(PiD)
    ZD = np.linalg.inv(I - P + PiD)
    #print(ZD)
    DD = np.linalg.inv(np.diag(np.diag(PiD)))
    #print(DD)
    MD = (I - ZD + E @ np.diag(np.diag(ZD))) @ DD
    print(MD)
    return MD

In [25]:
# Example matrix P
P = np.array([[0.4211, 0.4247, 0.1542],
              [0.2808, 0.2743, 0.445 ],
              [0.9873, 0.3257, 0.1018]])

# Running the function with the provided matrix
jjhunter(P)

[[2.12465365 2.41503427 5.288825  ]
 [2.10789656 2.82436685 3.95190861]
 [1.03325414 2.57366158 5.70537237]]


array([[2.12465365, 2.41503427, 5.288825  ],
       [2.10789656, 2.82436685, 3.95190861],
       [1.03325414, 2.57366158, 5.70537237]])